# Generated by Django 5.1.1 on 2024-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_moodentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
